name: TERRAFORM PRECOMMIT HOOKS

on:
  pull_request:
  push:
    branches: [ main, develop, feature/**, nanlabs_challenge]

jobs:
  precommit:
    runs-on: ubuntu-latest
    name: Run Terraform Pre-Commit Checks

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.9.17
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.17'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Install terraform-docs
        run: |
          curl -Lo terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-linux-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          sudo mv terraform-docs /usr/local/bin/
          terraform-docs --version

      - name: Install pre-commit
        run: pip install pre-commit